In [32]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [33]:
from sklearn.pipeline import * 
from sklearn.naive_bayes import * 
from sklearn.cluster import *  
from sklearn.covariance import *  
from sklearn.cross_decomposition import *  
from sklearn.datasets import *  
from sklearn.decomposition import *  
from sklearn.ensemble import *  
from sklearn.feature_extraction import *  
from sklearn.feature_extraction.text import *  
from sklearn.feature_selection import *  
from sklearn.gaussian_process import *  
from sklearn.linear_model import *  
from sklearn.manifold import *  
from sklearn.metrics import *  
from sklearn.mixture import *  
from sklearn.model_selection import *  
from sklearn.neighbors import *  
from sklearn.neural_network import *  
from sklearn.preprocessing import *  
from sklearn_pandas import DataFrameMapper
from sklearn.svm import *  
from sklearn.tree import *  
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [34]:
import keras_tuner
import keras
from keras.models import Sequential, load_model
from keras.layers import Dense, Input
from keras.wrappers import SKLearnClassifier
import keras.utils 
from keras.callbacks import * 

<h2>Question-26</h2>
# HandsOn - Predict The Data Scientists Salary In India from kaggle use sklearn
dataset: Predict-The-Data-Scientists-Salary-In-India_Train_Dataset.csv
Data Features:
    Name of the company (Encoded)
    Years of experience(split to min and max experience)
    Job description
    Job designation
    Job Type
    Key skills
    Location (needs LabelEncoded)
    Salary in Rupees Lakhs(To be predicted)(needs LabelEncoded)
    
Find the best estimator among below 
clf1 = DecisionTreeClassifier()
clf2 = RandomForestClassifier(n_estimators=100)
clf3 = ExtraTreesClassifier(n_estimators=100)
clf4 =  AdaBoostClassifier(n_estimators=100)
clf5 =  GradientBoostingClassifier(n_estimators=100)

In [4]:
#loading datsset
scientist_sal = pd.read_csv('code\data\Predict-The-Data-Scientists-Salary-In-India_Train_Dataset.csv')

In [6]:
scientist_sal.head()

Unnamed: 0 experience                                    job_description  \
0           0    5-7 yrs  Exp: Minimum 5 years;Good understanding of IOC...   
1           1  10-17 yrs  He should have handled a team of atleast 5-6 d...   
2           2    5-9 yrs  Must be an effective communicator (written & s...   
3           3   7-10 yrs  7  -  10 years of overall experience in data e...   
4           4    1-3 yrs  Chartered Accountancy degree or MBA in Finance...   

                                           job_desig   job_type  \
0        Senior Exploit and Vulnerability Researcher        NaN   
1                                           Head SCM        NaN   
2  Deputy Manager - Talent Management & Leadershi...  Analytics   
3                 Associate Manager Data Engineering  Analytics   
4                            TS- GSA- Senior Analyst        NaN   

                                          key_skills               location  \
0  team skills, communication skills, analytical ...  Delhi NCR(Vikas Puri)   
1  ppc, logistics, inventory management, supply c...                Sonepat   
2  HR Analytics, Employee Engagement, Training, S...              Delhi NCR   
3  SQL, Javascript, Automation, Python, Ruby, Ana...              Bengaluru   
4  accounting, finance, cash flow, financial plan...                Gurgaon   

   salary  company_name_encoded  
0   6to10                  3687  
1  10to15                   458  
2  15to25                  4195  
3  10to15                   313  
4    3to6                  1305

In [7]:
scientist_sal.columns

Index(['Unnamed: 0', 'experience', 'job_description', 'job_desig', 'job_type',
       'key_skills', 'location', 'salary', 'company_name_encoded'],
      dtype='object')

In [81]:
# splitting experience into min_experience and max_experience and converting it to numeric
scientist_sal[['min_experience', 'max_experience']] = scientist_sal['experience'].str.split('-', expand=True)
scientist_sal['min_experience'] = scientist_sal['min_experience'].str.extract('(\d+)').astype(float)
scientist_sal['max_experience'] = scientist_sal['max_experience'].str.extract('(\d+)').astype(float)

In [82]:
scientist_sal.drop('experience', axis=1, inplace=True)

In [83]:
# Label encoding
columns = ['job_description', 'job_desig', 'job_type', 'key_skills', 'location', 'salary']
label_encoders = {}
for col in columns:
    le = LabelEncoder()
    scientist_sal[col] = le.fit_transform(scientist_sal[col].astype(str))
    label_encoders[col] = le

In [84]:
X = scientist_sal.drop('salary', axis=1)
y = scientist_sal['salary']

In [105]:
#split test train, test=0.2
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [106]:
#classifiers
clf1 = DecisionTreeClassifier()
clf2 = RandomForestClassifier(n_estimators=100)
clf3 = ExtraTreesClassifier(n_estimators=100)
clf4 = AdaBoostClassifier(n_estimators=100)
clf5 = GradientBoostingClassifier(n_estimators=100)

In [107]:
#pipelines
pipe1 = Pipeline([('clf', clf1)])
pipe2 = Pipeline([('clf', clf2)])
pipe3 = Pipeline([('clf', clf3)])
pipe4 = Pipeline([('clf', clf4)])
pipe5 = Pipeline([('clf', clf5)])

In [108]:
#params
param1 = {'max_depth': [3, 5, 10, None], 'min_samples_split': [2, 5, 10]}
param2 = {'n_estimators': [50, 100, 150], 'max_depth': [5, 10, None]}
param3 = {'n_estimators': [50, 100, 150], 'max_depth': [5, 10, None]}
param4 =  {'n_estimators': [50, 100, 150], 'learning_rate': [0.5, 1.0, 1.5]}
param5 = {'n_estimators': [50, 100, 150], 'learning_rate': [0.05, 0.1, 0.2], 'max_depth': [3, 5, 7]}

In [109]:
#training each classifier
classifiers = [clf1, clf2, clf3, clf4, clf5]
names = ['DecisionTree', 'RandomForest', 'ExtraTrees', 'AdaBoost', 'GradientBoosting']
for clf, name in zip(classifiers,names):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    # printing accuracy and confusion matrix
    acc = accuracy_score(y_test, y_pred)
    print(f"{name} Accuracy: {acc}")
    print(f"Confusion Matrix for {name}:\n{confusion_matrix(y_test, y_pred)}")
    print("-" * 50)

DecisionTree Accuracy: 0.3511739459732391
Confusion Matrix for DecisionTree:
[[339  47  33   6 136  77]
 [ 42 274 253  47  69 201]
 [ 25 298 265 126  49 114]
 [  7  35 102 141   6  15]
 [138  68  38   4 179 116]
 [ 54 198  94  19 153 193]]
--------------------------------------------------
RandomForest Accuracy: 0.39232517041151227
Confusion Matrix for RandomForest:
[[446  30  13   0 102  47]
 [ 28 338 286  10  47 177]
 [ 14 354 289 118  12  90]
 [  3  20 125 152   1   5]
 [158  59  25   1 166 134]
 [ 58 240 107   7 136 163]]
--------------------------------------------------
ExtraTrees Accuracy: 0.3706134814440798
Confusion Matrix for ExtraTrees:
[[430  35  11   0 115  47]
 [ 33 302 277  18  56 200]
 [ 15 354 276 135   9  88]
 [  4  20 130 147   1   4]
 [157  55  23   1 164 143]
 [ 52 255  93   8 154 149]]
--------------------------------------------------
AdaBoost Accuracy: 0.3976268619035597
Confusion Matrix for AdaBoost:
[[477  30  18   1  66  46]
 [ 48 267 292  28  98 153]
 [ 24 2

In [81]:
# we can say that gradient boosting is performing better than all other classifiers

<h2>Question-27</h2>
# HandsOn - Titanic survival prediction , from Kaggle
https://www.kaggle.com/c/titanic/data
           
Understand data, download only train.csv and test.csv 

Using Tpot, find the test score of best Estimator 
Hint:
The first and most important step in using TPOT on any data set 
is to rename the target class/response variable to 'class'.

At present, TPOT requires all the data to be in numerical format. 
Categorical:  Name, Sex, Ticket, Cabin and Embarked.
So convert categorical to number(which preprocessing?) and/or 
discard high levels of categorical completely 

In [110]:
from tpot import TPOTClassifier

In [130]:
#loading training and testing dataset
train = pd.read_csv("code/data/titanic_train.csv")

In [131]:
train.columns

Index(['survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked'],
      dtype='object')

In [132]:
train.head()

survived  pclass                                               name  \
0         0       3                            Braund, Mr. Owen Harris   
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2         1       3                             Heikkinen, Miss. Laina   
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4         0       3                           Allen, Mr. William Henry   

      sex   age  sibsp  parch            ticket     fare cabin embarked  
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S  
1  female  38.0      1      0          PC 17599  71.2833   C85        C  
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
3  female  35.0      1      0            113803  53.1000  C123        S  
4    male  35.0      0      0            373450   8.0500   NaN        S

In [133]:
#renaming the traget class name to class
train = train.rename(columns={"survived": "class"})


In [134]:
# keeping only relevant columns and dropping high levels of categorical completely
train = train[['class', 'pclass','sex', 'age', 'sibsp', 'parch', 'fare', 'embarked']]

In [140]:
#filling the missing values in the dataset
train["age"].fillna(train["age"].median(), inplace=True)
train["embarked"].fillna(train["embarked"].mode()[0], inplace=True)


C:\Users\Bhavya\AppData\Local\Temp\ipykernel_10944\1381348903.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train["age"].fillna(train["age"].median(), inplace=True)
C:\Users\Bhavya\AppData\Local\Temp\ipykernel_10944\1381348903.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy

In [141]:
# encoding categorical variables
train['sex'] = train['sex'].map({'male': 0, 'female': 1})
train['embarked'] = train['embarked'].map({'S': 0, 'C': 1, 'Q': 2})

In [142]:
#train and target variables
X = train.drop(columns=["class"])
y = train["class"]

In [143]:
# splitting the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [144]:
# tpot
tpot = TPOTClassifier(generations=5, population_size=20, verbosity=2, random_state=42)
tpot.fit(X_train, y_train)

is_classifier
is_regressor
is_classifier


C:\Users\Bhavya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1230: FutureWarning: passing a class to None is deprecated and will be removed in 1.8. Use an instance of the class instead.
  warnings.warn(
C:\Users\Bhavya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1270: FutureWarning: passing a class to None is deprecated and will be removed in 1.8. Use an instance of the class instead.
  warnings.warn(


is_regressor
is_classifier
is_regressor
is_classifier
is_classifier
is_classifier
is_classifier
is_regressor
is_classifier
is_regressor
is_classifier
is_regressor
is_classifier
is_regressor
is_classifier
is_regressor
is_classifier
is_regressor
is_classifier
is_regressor
is_classifier
is_classifier
is_classifier
is_classifier
is_classifier
is_classifier
is_classifier
is_classifier
is_regressor
is_classifier
is_regressor
is_classifier
is_regressor
is_classifier
is_regressor
is_classifier
is_regressor
is_classifier
is_regressor
is_classifier
is_regressor
is_classifier
is_classifier
is_classifier
is_regressor
is_classifier
is_regressor
is_classifier


Version 0.12.2 of tpot is outdated. Version 1.0.0 was released Wednesday February 26, 2025.
C:\Users\Bhavya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\impute\_base.py:635: UserWarning: Skipping features without any observed values: ['sex' 'embarked']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(


Imputing missing values in feature set


Optimization Progress:   0%|          | 0/120 [00:00<?, ?pipeline/s]


Generation 1 - Current best internal CV score: 0.7444203683640304

Generation 2 - Current best internal CV score: 0.754240126071112

Generation 3 - Current best internal CV score: 0.754240126071112

Generation 4 - Current best internal CV score: 0.754240126071112

Generation 5 - Current best internal CV score: 0.754240126071112

Best pipeline: RandomForestClassifier(BernoulliNB(MinMaxScaler(input_matrix), alpha=0.001, fit_prior=False), bootstrap=True, criterion=gini, max_features=0.2, min_samples_leaf=8, min_samples_split=4, n_estimators=100)


TPOTClassifier(generations=5, population_size=20, random_state=42, verbosity=2)

In [153]:
#See score and generate file 
print(tpot.score(X_train, y_train), tpot.score(X_test, y_test))
tpot.export("tpot_ques27_day12_titanic.py")
yHat = tpot.predict(X_test)

Imputing missing values in feature set
Imputing missing values in feature set
0.7808988764044944 0.6759776536312849
Imputing missing values in feature set


C:\Users\Bhavya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\impute\_base.py:635: UserWarning: Skipping features without any observed values: ['sex' 'embarked']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
C:\Users\Bhavya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\impute\_base.py:635: UserWarning: Skipping features without any observed values: ['sex' 'embarked']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(
C:\Users\Bhavya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\impute\_base.py:635: UserWarning: Skipping features without any observed values: ['sex' 'embarked']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(


In [149]:
%pycat tpot_ques27_day12_titanic.py

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.pipeline import make_pipeline, make_union
from sklearn.preprocessing import MinMaxScaler
from tpot.builtins import StackingEstimator
from sklearn.impute import SimpleImputer
from tpot.export_utils import set_param_recursive

# NOTE: Make sure that the outcome column is labeled 'target' in the data file
tpot_data = pd.read_csv('PATH/TO/DATA/FILE', sep='COLUMN_SEPARATOR', dtype=np.float64)
features = tpot_data.drop('target', axis=1)
training_features, testing_features, training_target, testing_target = \
            train_test_split(features, tpot_data['target'], random_state=42)

imputer = SimpleImputer(strategy="median")
imputer.fit(training_features)
training_features = imputer.transform(training_features)
testing_features = imputer.transform(testing_features)

# Average CV score on the 

In [154]:
test_accuracy = tpot.score(X_test, y_test)
print(f"Test Accuracy: {test_accuracy}")

Imputing missing values in feature set
Test Accuracy: 0.6759776536312849


C:\Users\Bhavya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\impute\_base.py:635: UserWarning: Skipping features without any observed values: ['sex' 'embarked']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(


In [155]:
# testing with test dataset

test_data = pd.read_csv('code/data/titanic_test.csv')

In [156]:
test.head()

pclass  sex   age  sibsp  parch     fare  embarked
0       3    1  34.5      0      0   7.8292         1
1       3    0  47.0      1      0   7.0000         2
2       2    1  62.0      0      0   9.6875         1
3       3    1  27.0      0      0   8.6625         2
4       3    0  22.0      1      1  12.2875         2

In [157]:
test_data = test_data[['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked']]

In [158]:
test_data['age'].fillna(test_data['age'].median(), inplace=True)
test_data['fare'].fillna(test_data['fare'].median(), inplace=True)
test_data['embarked'].fillna(test_data['embarked'].mode()[0], inplace=True)

C:\Users\Bhavya\AppData\Local\Temp\ipykernel_10944\2386384664.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_data['age'].fillna(test_data['age'].median(), inplace=True)
C:\Users\Bhavya\AppData\Local\Temp\ipykernel_10944\2386384664.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves a

In [159]:
test_data['sex'] = test_data['sex'].map({'male': 0, 'female': 1})
test_data['embarked'] = test_data['embarked'].map({'S': 0, 'C': 1, 'Q': 2})

In [160]:
#predicting the survival outcome for the test set
predictions = tpot.predict(test_data)

Imputing missing values in feature set


C:\Users\Bhavya\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\impute\_base.py:635: UserWarning: Skipping features without any observed values: ['sex' 'embarked']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(


In [161]:
print(predictions)

[0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0
 1 1 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0
 1 1 1 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 1 0 1 1 0 1
 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 0 0 0 1 0 0 0 0 0 1 0 0 1 0 1 0 1 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0 0
 0 0 0 1 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 0
 1 0 0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0 1 1 0
 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0
 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 0 1 0 0 1 0 1 0 1 0 0
 1 0 1 0 1 0 0 1 0 0 0]


<h2> Keras:
data/pima-indians-diabetes.csv, Binary classification </h2>

In [35]:
# loading the dataset
pima = pd.read_csv('code/data/pima-indians-diabetes.csv', header=None)

In [36]:
pima.head()

0    1   2   3    4     5      6   7  8
0  6  148  72  35    0  33.6  0.627  50  1
1  1   85  66  29    0  26.6  0.351  31  0
2  8  183  64   0    0  23.3  0.672  32  1
3  1   89  66  23   94  28.1  0.167  21  0
4  0  137  40  35  168  43.1  2.288  33  1

In [92]:
len(pima)

768

In [93]:
X = pima.iloc[:, :-1].values
y = pima.iloc[:, -1].values

In [94]:
#feature scaling
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [95]:
#splitting the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [96]:
# defining the model
model = Sequential()
model.add(Dense(12,input_dim=8,activation='relu'))
model.add(Dense(8,activation='relu')) # relu activation for hidden layers
model.add(Dense(1,activation='sigmoid')) # since it is binary classification, we usse sigmoid func

C:\Users\Bhavya\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [97]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) #compilation of model

In [98]:
model.fit(X_train, y_train, epochs=120, batch_size=10, verbose=1)

Epoch 1/120
62/62 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.4908 - loss: 0.7001
Epoch 2/120
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6664 - loss: 0.6397
Epoch 3/120
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6849 - loss: 0.5929
Epoch 4/120
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7285 - loss: 0.5462
Epoch 5/120
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7694 - loss: 0.5119
Epoch 6/120
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7555 - loss: 0.4986
Epoch 7/120
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7395 - loss: 0.5073
Epoch 8/120
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7695 - loss: 0.4661
Epoch 9/120
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7763 - loss: 0.4590
Epoch 10/120
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7595 - loss: 0.4694
Epoch 11/120
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7599 - loss: 0.4462
Epoch 12/120
62/62 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy:

In [99]:
#model evaluation
loss, accuracy = model.evaluate(X_test, y_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7671 - loss: 0.5018 


In [100]:
accuracy

0.7662337422370911